name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman
        run: sudo apt-get update && sudo apt-get install -y podman

      - name: Build image with Podman
        run: podman build -t hello-world .

      - name: Run container
        run: podman run --rm hello-world
